apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      volumes:
        - name: web-volume
          configMap:
            name: app-one-web
      containers:
        - name: app-one
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-volume
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              memory: "32Mi"
              cpu: 250m
            limits:
              memory: "128Mi"
              cpu: 500m
