apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      volumes:
        - name: web-volume
          configMap:
            name: app-two-web
      containers:
        - name: app-two
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-volume
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              memory: "32Mi"
              cpu: 250m
            limits:
              memory: "128Mi"
              cpu: 500m
