# Queries variable from environ.
# If the value is inexistant or empty, exit the program.
def pull_env(name)
  var = ENV[name]
  if var.nil? || var.empty?
    print "Missing or empty environment variable (#{name})\n"
    exit! 1
  end
  return var
end

# Config variables
LOGIN = pull_env('LOGIN_42')
SERVER_IP = pull_env('SERVER_IP')
WORKER_IP = pull_env('WORKER_IP')

# Vagrant configuration
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"

  # to share the k3s token between hosts
  config.vm.synced_folder "shared", "/vagrant"

  # k3s server
  config.vm.define "#{LOGIN}S" do |server|
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provision "shell",
      path: "guests/setup_k3s.sh",
      args: "server"
  end

  # k3s server worker
  config.vm.define "#{LOGIN}SW" do |worker|
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provision "shell",
      path: "guests/setup_k3s.sh",
      args: "agent"
  end

  # Virtual Box VM config
  config.vm.provider "virtualbox" do |vbox|
    # as per the subject
    vbox.memory = "1024" # MiB
    vbox.cpus = 2
  end
end

# -*- mode: ruby -*-
# vi: set ft=ruby :
