# This is now part of the demostanis/amassias repository.
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: deployment
#  namespace: dev
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: playground
#  template:
#    metadata:
#      labels:
#        app: playground
#    spec:
#      containers:
#        - name: playground
#          image: wil42/playground:v1
#          ports:
#            - containerPort: 8888
#
#---
#
apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: playground
  ports:
    - port: 8888

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: playground-route
  namespace: dev
spec:
  routes:
    - kind: Rule
      match: Path(`/`)
      services:
        - name: playground-service
          port: 8888
