apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - name: playground
          image: wil42/playground:v1
          ports:
            - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: playground
  ports:
    - port: 8888

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: playground-service
            port:
              number: 8888
